Felix/seed data creation
hoguer/porto3000 pull request #26
Opened 2022-01-26 06:23 UTC by Felix-Cadiz

Formatted index.db and added seed data for wines in init_db. Cheeses functions will be added later.

2022-01-26 07:09 UTC, kbonifacio approved these changes
lgtm

2022-01-26 14:24 UTC, Felix-Cadiz reviewed
LGTM! Thanks for the great descriptions!

2022-01-27 00:56 UTC, kbonifacio requested changes
Just caught a spelling error for the Wensleydale cheese in the name. Other than that the code looks good for the new cheeses.

2022-01-27 00:56 UTC, kbonifacio commented on db/init_db.js
> +        name: "Extra Mature Real Yorkshire Wensleydalee",
Please change Wensleydalee to **Wensleydale** unless this was intentional then ignore.

2022-01-27 01:28 UTC, Felix-Cadiz commented
Nice catch and even better descriptions! Everything else looks good, especially id:44.

2022-01-27 01:36 UTC, kbonifacio commented on db/init_db.js
> +        name: "Extra Mature Real Yorkshire Wensleydalee",
Pushing through for code review, will resolve later tonight.

2022-01-27 01:37 UTC, merged

2022-01-27 01:37 UTC, kbonifacio commented
Will resolve cheese update requests later tonight during the breakout. Pushing through for code review.